language: r
sudo: false
r: devel
cache: packages

latex: true


env:
  matrix: 
    - CXX_OLEVEL=2 CXX=clang++

before_install:
  - mkdir -p ~/.R/
  - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ~/.R/Makevars 
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars

script: 
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check rstap*tar.gz

after_script:
  - tar -ztvf rstap_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - Rscript - e 'pkgdown::build_site()'

after_failure:
  - cat rstap.Rcheck/00*

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_PAT
    keep-history: true
    local-dir: docs
    on:
        branch: master
