language: r
sudo: false
r: devel
cache: packages

latex: true
r_build_args: "--no-build-vignettes"
r_check_args: "--ignore-vignettes"

matrix: 
  include:
    - os: linux 
        addons:
           apt:
             sources:
                 - ubuntu-toolchain-r-test
             packages:
                 - g++-7
    - env:
        - MATRIX_EVAL = "CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars 

script: 
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check rstap*tar.gz

after_script:
  - tar -ztvf rstap_*.tar.gz
  - echo ${NOT_CRAN}


after_failure:
  - cat rstap.Rcheck/00*

